### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ryanblock**
### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [ ] Forked the repo and created your branch from `master`
- [ ] Made sure tests pass (run `npm it` from the repo root)
- [ ] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation:
  - [ ] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [ ] Summarized your changes in `changelog.md`
- [ ] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by ryanblock** [comment]
@metadaddy, would love for you to take a look at https://github.com/architect/aws-lite/pull/104/commits/d49503c06eb6c03616e3b386f7f3d12c821105bf

I have some mixed feelings in the implementation, wherein I yanked out `s3rver`'s mocked responses and used them as fixtures in the S3 mocks. Because XML → data can get so funky, I felt the best way to ensure it interpolated exactly as it would have before would be just use the raw XML strings, and parse them as we would otherwise. However, I acknowledge this may increase maintenance overhead of the S3 test suite since we now have to maintain those XML response fixtures; adding and testing new methods will be a bit more complex and annoying moving forward.

That said, I really like the result, in which our own plugins exercise the unit testing system, while also improving test speeds and removing a very large dev dep and the DNS workarounds. Thank you again for getting this test suite to this place; when I began working on the integrated unit testing, I wanted plugins to be a prime use case so we could expand and improve their testing across the board. Having this test suite on hand was really wonderful, I appreciate the care you put into it (especially including the comments on how we can improve our methods' output).

**Comment by metadaddy** [comment]
Hi @ryanblock - I totally understand your reasoning. I don't have any ego wrapped up in this - if it's the right thing to do, then have at it. I'm glad my initial implementation helped push the ball forward!

One beneficial effect of this new approach is that we can use responses from the actual AWS service(s), with no risk that the mock service deviates from the canonical implementation. Given that `s3rver` appears to have been abandoned (last commit was 3 years ago), I was already a little uncomfortable in that is was just a matter of time before we encountered an S3 feature that `s3rver` does not implement.

One thought - would it be worth writing a set of scripts that run through series of operations against live AWS services, saving the requests and responses for use here?

**Comment by metadaddy** [comment]
One thing I don't see is any testing that the outgoing request from `aws-lib` is correct - i.e. it contains all of the mandatory elements, none that are unexpected, etc. I wonder if it would be straightforward to check that requests conform to https://doc.s3.amazonaws.com/2006-03-01/AmazonS3.xsd - or would that be overkill?

**Comment by metadaddy** [comment]
OK - I spent the last two hours discovering that [AmazonS3.xsd](https://doc.s3.amazonaws.com/2006-03-01/AmazonS3.xsd) is specifically the schema for the (pretty much obsolete) [Amazon S3 SOAP API](https://docs.aws.amazon.com/AmazonS3/latest/API/APISoap.html), and it doesn't match the [Amazon S3 REST API](https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html). The canonical schema appears to be the Smithy model: [s3.json](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/sdk-codegen/aws-models/s3.json).

I'm guessing there's a way to validate a couple of hundred bytes of XML against this 2 MB JSON model, but I'm wondering whether that's worthwhile :confused:

Is there an easier way to validate that `aws-lite` is emitting a valid request?

**Comment by ryanblock** [comment]
@metadaddy super appreciate that! Also, excellent point about `s3rver` being abandoned, I forgot about that. Definitely thinking this is the right approach.

A script that can occasionally run through live AWS services and generates mocks would be amazing, love that idea. A bit of a tall order, though. (We presently do some super basic validation through the [`test:live` suite](https://github.com/architect/aws-lite/tree/main/test/live).)

I super appreciate your taking the time to investigate the schemas, that's great work that will help inform our decisions here!

Re. outgoing request validation, all these requests have thus far been manually validated on live S3 resources, and I feel comfortable with that approach (more there in a moment). Given the fact that AWS doesn't publish OpenAPI definitions, and that their APIs don't break (generally), I don't feel this approach is cowboy.

Moreover, looking over that `s3.json` file, my sense is that it's probably going to cause more issues than it would resolve for us to use that format as a validation mechanism. Those schemas are authored for Smithy, and that doesn't fundamentally guarantee we won't have issues. (They make break the schema accidentally, or introduce breaking changes to Smithy's interpretation of the schemas.) My view, and I don't know if it's shared, is that:

- Ultimately each SDK represents an abstraction for the API, and the interpretation of that abstraction is encoded one way or another into a source of truth – be it a json file that is used by a tool like Smithy to generate SDK code, or by our own request / response functions
- No matter what, we have to manually validate all this against the API anyway
- AWS really does not break its APIs

So for the above reasons, I'm personally fine for our source of truth to be business logic that we've validated and proven. If issues arise, we will fix them promptly (and as ever, PRs are accepted). Wdyt?

**Comment by metadaddy** [comment]
@ryanblock I think a pragmatic approach is best. On that topic, I notice there's a 'live' test for the `lambda` plugin. Presumably someone runs that manually with the appropriate environment variables? Anything I should know before I implement a similar test for `s3`?

**Comment by ryanblock** [comment]
The `test:live` runs as a final "Hey, this all actually does work with real AWS" validation in CI: https://github.com/architect/aws-lite/blob/main/.github/workflows/build.yml#L48-L54 It's intended to be fast and simple, and only to prove that aws-lite does in fact work at all.

The S3 response caching we were discussing is going to be a lot more complex, with a few different resources, and a variety of different calls – and not something we'd want to run as part of the test suite every single time, imo, as it would be too slow. I'm thinking it should be a script we can run periodically, as we see fit, that we can use to update response mocks. wdyt?

**Comment by metadaddy** [comment]
> The S3 response caching we were discussing is going to be a lot more complex...

Agreed. Is there a place for a quick live test for S3, though? The minimal test would be one API call to `ListBuckets`, which should always succeed, assuming the API key has the correct perms. That would be enough to check that everything is wired up, the request URL and its signature are being generated correctly, and the response can be parsed.

**Comment by ryanblock** [comment]
I can think of a few places! What would the purpose of a live S3 test be? We have presumably already proven that `aws-lite` can correctly communicate with AWS via the live Lambda test, no?

**Pull request merged**
