### PR TITLE
Add S3 tests

### PR DESCRIPTION
**Pull request by metadaddy**
- Added tests using [s3rver](https://github.com/jamhall/s3rver) as mock S3 service.
- Fixed configuration and tests to use virtual host-style S3 URLs rather than path-style.
- Merged with current main.
- Fixed tests to expect numeric counts, e.g. `0`, rather than strings, e.g. `"0"`.

All tests pass, verified by hand that it works with both Amazon S3 and Backblaze B2.

### CODE REVIEW

**Comment by ryanblock** [comment]
Thanks for your patience @metadaddy! Have you been developing this branch on a Linux or Windows box? I ask because I stepped through each of the 4 commits following https://github.com/architect/aws-lite/pull/73/commits/b3e69e68e33c8e137bb46c467f089121d6fd4542 and none of them pass tests on my Mac.

Perhaps not entirely surprising, I've seen Node.js do some funky, irregular things related to DNS resolution over the years across platforms – especially related to localhost / loopback / 127.0.0.1 / ::1, etc. (This is not an indictment of Node.js, more just the reality of the vagaries of hooking into platform-specific networking stack behavior.)

I took a look into s3rver's issues and couldn't find much useful in there about virtual host-style address emulation. I hate to say it but going [back to this](https://github.com/architect/aws-lite/pull/59):

> Just to get things working and be able to continue the conversation I'm going to implement a testing conditional in the S3 plugin's host() method, using the path-style bucket addresses, but that's a gnarly hack and I'd really like to see if we can come up with any better ways of handling this before merging. What do you think?

I think we have the answer to that question: you did the diligence, and I'm not sure there's actually a better, more reliable cross-platform way to execute this particular code path than that ugly testing conditional. Sigh. Once more I turn the mic back to you for your thoughts!

**Comment by metadaddy** [comment]
Hi @ryanblock - I've been developing on a Mac. I just realized that the issue might be ipv4 vs ipv6. The test client tries to connect on ipv4, but, if the server is listening on ipv6, it won't be able to connect. I can force the server to listen on ipv4 by specifying the listening address. I'll try that, and possibly a couple of other things, before I resort to `if (testing)`!

**Comment by metadaddy** [comment]
This still looks like it's an ipv4 vs ipv6 thing: `Error: @aws-lite/client: S3.ListBuckets: connect ECONNREFUSED ::1:4569`

**Comment by metadaddy** [comment]
Cracked it!

Basically, when the server listens, then when the client connects, it's pretty much a coin-toss whether each will use ipv4 (`127.0.0.1`) or ipv6 (`::1`)–see https://github.com/node-fetch/node-fetch/issues/1624. You have to set a consistent DNS result order to guarantee that the client and server use the same IP version.

**Comment by ryanblock** [comment]
Thanks for your patience, and for figuring this out. Funky behavior.

This is looking good, and works well on my machine. I have to admit, I don't love the fact that it's using a non-local resource to run this test suite, which means our ability to pass tests and ship releases will now be dependent on `localtest.me` being online, and there's very little information about how they're hosting, what reliability level they're attempting to achieve, etc.

I'm thinking perhaps using something like [`evil-dns`](https://www.npmjs.com/package/evil-dns) could be preferable, but perhaps we'll save that exercise for another day.

What's the status with #72? And is this PR ready to merge (presumably into #59)?

**Comment by metadaddy** [comment]
Hi @ryanblock - over on Discord, you said:

> If you haven’t already pls do merge in main, there’s been a fair bit of work to the s3 plugin lately

So this PR does exactly that - merges all of the plugin/S3 testing work into `architect:main`, making #72 redundant, since that PR is based on `architect:plugin-tests`. If I've done this correctly, you can just abandon #72 and the `architect:plugin-tests` branch.

If I misinterpreted your request, let me know and I'll rework this as appropriate.

> I'm thinking perhaps using something like [evil-dns](https://www.npmjs.com/package/evil-dns) could be preferable, but perhaps we'll save that exercise for another day.

Yeah - as soon as this is merged, I'll create an issue to switch to evil-dns, and give it a try. It should be very straightforward.

**Comment by metadaddy** [comment]
@ryanblock I took at quick look at `[evil-dns](https://www.npmjs.com/package/evil-dns)`, and it looked pretty straightforward, so I went ahead and ripped out `localtest.me`. All worked on my machine, but now I see we have the same issue with connection errors in the CI. I'll research how to straighten that out.

**Comment by metadaddy** [comment]
That did the trick. The issue was that `s3rver` used `localhost` as its default address so, on the CI machines, the server was listening on IPv6, while the client was connecting to `127.0.0.1` on IPv4. Setting `s3rver`'s `address` to `127.0.0.1` forces it to listen on IPv4.

**Pull request merged**
